export const SET_TASKS_TO_SHOW = 'SET_TASKS_TO_SHOW';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE';
export const CHANGE_SORT = 'CHANGE_SORT';
export const ADD_GRID_STATE = 'ADD_GRID_STATE';